<a href="https://colab.research.google.com/github/sniggel/coursera-deeplearning.ai/blob/master/Week2_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 2 Notes


In [1]:
import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

## Vectorized implementation
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorized version: " + str(toc-tic) + "ms")

## Non-Vectorized implementation
c = 0
tic = time.time()
for i in range(1000000):
  c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop: " + str(1000*(toc-tic)) + "ms")


250092.51633280987
Vectorized version: 0.002269268035888672ms
250092.51633280097
For loop: 499.32193756103516ms


# Broadcasting example

Calories from Carbs, Proteins, Fats in 100g of different foods:

Type | Apples | Beef |  Potatoes
--- | --- | --- | ---
Carb | 56.0 | 0.0 | 4.4 | 68.0
Protein| 1.2 | 104.0 | 52.0 | 8.0
Fat | 1.8 | 135.0 | 99.0 | 0.9
--- | --- | --- | --- | ---
total | 59.0 | 139.0 | 155.4 |  76.9

Calculate the % of calories from Carbs, Proteins and Fats

In [8]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8,135.0,99.0,0.9]])

print(A)

cal = A.sum(axis=0)
print(cal)

percentage = 100*A/cal
print(percentage)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# A note on python/numpy vectors

In [12]:
import numpy as np

## Creates a datastructure: rank1 array (not consistent, do not use)
a = np.random.randn(5)
print(a)

print(a.shape)

## transpose
print(a.T)

print(np.dot(a,a.T))

## Proper way to init a 5*1 matrix
## always use randn(5,1) or randn(1,5)
## row vector: randn(5,1)
## column vector: randn(1,5)
a = np.random.randn(5,1)
print(a)

## Transpose to a row vector, gives a 1x5 matrix
print(a.T)

print(np.dot(a,a.T))

assert(a.shape == (5,1))

[ 0.07072448  1.34623086 -1.21354045  0.70406356 -0.38140447]
(5,)
[ 0.07072448  1.34623086 -1.21354045  0.70406356 -0.38140447]
3.9311947841205694
[[ 1.11701756]
 [ 1.09746352]
 [ 0.94196229]
 [-0.52370767]
 [-0.80244273]]
[[ 1.11701756  1.09746352  0.94196229 -0.52370767 -0.80244273]]
[[ 1.24772824  1.22588602  1.05218842 -0.58499067 -0.89634263]
 [ 1.22588602  1.20442617  1.03376925 -0.57475007 -0.88065162]
 [ 1.05218842  1.03376925  0.88729296 -0.49331288 -0.75587079]
 [-0.58499067 -0.57475007 -0.49331288  0.27426973  0.42024542]
 [-0.89634263 -0.88065162 -0.75587079  0.42024542  0.64391434]]
